FORMAT: 1A
HOST: https://bookings-api.seatris.com/
# Seatris Guest Booking

Seatris Guest Booking is an API allowing users to make reservations

# Group Restaurants

Resources related to restaurants in the API.

## Retrieve Restaurant Info [GET]
## Restaurant [/restaurants/{restaurant_id}]
+ Parameters
    + restaurant_id (number) - ID of the Restaurant in the form of an integer

+ Response 200 (application/json)
      {
        id: 1391,
        shifts: [{"id":51,"name":"Demo"}],
        floors: [{"id":0,"name":"all_floors"}],
        askForPreferences: true,
        shiftTemplates:
          [
            {
              "id":230,
              "floor_id":35,
              "name":"Dinner",
              "noshow_fee_currency":"EUR",
              "noshow_fee_cents":4000,
              "cancellation_limit_text":"15:00 am Tag der Buchung",
              "cancellation_limit_for_groups_text":"14:00 am Tag vor der Buchung",
              "booking_time_in_advance_minutes":-1
            },
            {
              "id":236,
              "floor_id":35,
              "name":"Dinner Di-Do",
              "noshow_fee_currency":"EUR",
              "noshow_fee_cents":0,
              "cancellation_limit_text":"15 Uhr am Tag der Reservierung",
              "cancellation_limit_for_groups_text":"",
              "booking_time_in_advance_minutes":-1
            }
          ]
        }


## Group Bookings

Resources related to bookings in the API.

### Create a New Booking [POST]
A reservation is done by creating a booking

+ Request (application/json)
