FORMAT: 1A
HOST: https://api-bookings.seatris.com/

# Seatris Guest Booking
Seatris Guest Booking is an API allowing users to make reservations


# GET /restaurants/{restaurant_id}
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug

+ Response 200 (application/json)

            {
              "id": 1391,
              "shifts": [{"id":51,"name":"Demo"}],
              "floors": [{"id":0,"name":"all_floors"}],
              "askForPreferences": true,
              "shiftTemplates":
              [
                {
                  "id": 230,
                  "floor_id": 35,
                  "name": "Dinner",
                  "noshow_fee_currency": "EUR",
                  "noshow_fee_cents": 4000,
                  "cancellation_limit_text": "15:00 am Tag der Buchung",
                  "cancellation_limit_for_groups_text": "14:00 am Tag vor der Buchung",
                  "booking_time_in_advance_minutes": -1
                },
                {
                  "id":236,
                  "floor_id":35,
                  "name":"Dinner Di-Do",
                  "noshow_fee_currency":"EUR",
                  "noshow_fee_cents":0,
                  "cancellation_limit_text":"15 Uhr am Tag der Reservierung",
                  "cancellation_limit_for_groups_text":"",
                  "booking_time_in_advance_minutes":-1
                }
              ]
            }

# GET /restaurants/{restaurant_id}/dates
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + persons (number, required) - the number of persons

+ Response 200 (application/json)

            {
              "foo": "bar"
            }

# GET /restaurants/{restaurant_id}/slots
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + persons (number, required) - the number of persons
+ Response 200 (application/json)

            {
              "foo": "bar"
            }


# POST /restaurants/{restaurant_id}/bookings/create

+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + locale (string, required) - the locale (de or en)
    + persons (number, required) - How many persons
    + user (user, required) - The first name of the main person

+ Request (application/json)

        {
              "persons": 2,
              "user" : {
                "firstname": "Martin",
                "lastname": "Wöginger",
                "email": "woeginger@exasoft.net",
                "gender": "male",
                "phone": "+491792404436",
                "restrictions": "Veganer",
                "restaurant_newsletter": true
              },
              "date": "2018-08-16",
              "time": "20:15",
              "sessionid": "f37681588d198288dec3bfd0ed",
              "isRequest": false,
              "shiftId": 193304,
              "cancel_limit": "10:00 Uhr am Tag vor der Buchung",
              "noshow_fee": "EUR 10",
              "notes_by_guest": "These are my notes"
          }
+ Response 200 (application/json)

    + Body

            {
              "success":true,
              "id":110504,
              "cancellation_token":"mut6FvW1pQtzwXYpeVsQ"
            }