FORMAT: 1A
HOST: https://api-bookings.seatris.com/

# Seatris Guest Booking
Seatris Guest Booking is an API allowing users to make reservations

# Data Structures

## Shift (object)

+ id (number) - Id of shift
+ name (string) - Name of shift

## Floor (object)

+ id (number) - Id of floor
+ name (string) - Name of floor

## Shifttemplate (object)

+ id (number) - Id of template
+ floor_id (number) - Id of floor
+ name (string) - Name of template
+ noshow_fee_currency (string) - Currency for noshow fee
+ noshow_fee_cents (number) - Amount for noshow fee (in cents)
+ cancellation_limit_text (string) - Hint text for cancellations
+ cancellation_limit_for_groups_text (string) - Hint text for cancellations for groups
+ booking_time_in_advance_minutes (number) - how many minutes a booking must be done before shift begin, -1 if there is no limit

## User (object)

+ firstname (string) - Firstname of user
+ lastname (string) - Lastname of user
+ email (string) - eMail of user
+ gender (string) - gender "male" or "female"
+ phone (string) - phone number of user
+ restrictions (string) - Comma seperated list of restrictions
+ restaurant_newsletter (boolean) - User wants a newsletter send


# GET /restaurants/{restaurant_id}
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug

+ Response 200 (application/json)

    + Attributes (object)
        + id: 1391 (number)
        + shifts: [{"id":51,"name":"Demo"}] (array[Shift]) - Array of Shifts
        + floors: [{"id":0,"name":"all_floors"}] (array[Floor]) - Array of Floors
        + prefered_locale: "en" (string) - The prefered locale
        + phone_prefix_code: "+49" (string)
        + guest_notes_for_booking_page: "<div style="text-align:center">"Our Mission" is to feed you great food.</div>" (string)
        + guest_notes_for_payment_page: "We kindly ask you to confirm your booking by entering your credit card details. Please, not that your table reservation is not confirmed without your credit card details." (string)
        + payment_provider: "adyen" (string)
        + checkout_image_url:  "https://seatris-production.s3.amazonaws.com/restaurants/checkout_images/000/001/317/default/AMADOR4.jpg" (string)
        + welcome_image_url: "https://finedining-production.s3.amazonaws.com/restaurants/welcome_images/000/001/317/default/AMADOR4_%282%29.jpg" (string)
        + address_line: "Borsigstraße 9, 10115, Berlin, Germany" (string)
        + conversion_tracking_url: "http://www.example.com" (string)
        + privacy_policy_url: "https://s3.eu-central-1.amazonaws.com/seatris-legal/Restaurant-Datenschutzerklaerung.pdf" (string) - URL to the privacy policy document in Guest-Bookings
        + max_party_size: 7 (number)
        + guest_booking_starting_from_hint: "We are taking online bookings for June onwards" (string)
        + name: "Demo" (string)
        + city: "Berlin" (string)
        + languages: ["DE", "EN"] (array[string])
        + phone: "+49 - 30 814540400" (string)
        + twitter: "https://twitter.com/SeatrisTeam" (string)
        + facebook: "https://www.facebook.com/seatris/" (string)
        + instagram "https://www.facebook.com/seatris/" (string)
        + email: "sales@seatris.com" (string)
        + askForPreferences: true (boolean) - User should be asked for preferences
        + shiftTemplates (array[Shifttemplate]) - Array of Shifttemplates

    + Body

            {
              "id": 1391,
              "prefered_locale": "de",
              "phone_prefix_code": "+49",
              "guest_notes_for_booking_page": "<div style='text-align:center'>Our Mission is to feed you great food.</div>",
              "guest_notes_for_payment_page": "We kindly ask you to confirm your booking by entering your credit card details. Please, not that your table reservation is not confirmed without your credit card details.",
              "payment_provider": "adyen",
              "checkout_image_url":"https://seatris-production.s3.amazonaws.com/restaurants/checkout_images/000/001/317/default/AMADOR4.jpg",
              "welcome_image_url":"https://finedining-production.s3.amazonaws.com/restaurants/welcome_images/000/001/317/default/AMADOR4_%282%29.jpg",
              "address_line": "Borsigstraße 9, 10115, Berlin, Germany",
              "conversion_tracking_url": "http://www.example.com",
              "privacy_policy_url": "https://s3.eu-central-1.amazonaws.com/seatris-legal/Restaurant-Datenschutzerklaerung.pdf",
              "max_party_size": 7,
              "guest_booking_starting_from_hint": "We are taking online bookings for June onwards",
              "name": "Demo",
              "city": "Berlin",
              "languages": ["DE", "EN"],
              "phone": "+49 - 30 814540400",
              "twitter": "https://twitter.com/SeatrisTeam",
              "facebook": "https://www.facebook.com/seatris/",
              "instagram" "https://www.facebook.com/seatris/",
              "email": "sales@seatris.com",
              "shifts": [{"id":51,"name":"Demo"}],
              "floors": [{"id":0,"name":"all_floors"}],
              "askForPreferences": true,
              "shiftTemplates":
              [
                {
                  "id": 230,
                  "floor_id": 35,
                  "name": "Dinner",
                  "noshow_fee_currency": "EUR",
                  "noshow_fee_cents": 4000,
                  "cancellation_limit_text": "15:00 am Tag der Buchung",
                  "cancellation_limit_for_groups_text": "14:00 am Tag vor der Buchung",
                  "booking_time_in_advance_minutes": -1
                },
                {
                  "id":236,
                  "floor_id":35,
                  "name":"Dinner Di-Do",
                  "noshow_fee_currency":"EUR",
                  "noshow_fee_cents":0,
                  "cancellation_limit_text":"15 Uhr am Tag der Reservierung",
                  "cancellation_limit_for_groups_text":"",
                  "booking_time_in_advance_minutes":-1
                }
              ]
            }

# GET /restaurants/{restaurant_id}/dates
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + persons (number, required) - the number of persons
    + start_date (string, required) - Date in form of 'YY-MM-DD' to start the search
    + end_date (string, required) - Date in form of 'YY-MM-DD' where search ends

+ Request (application/json)

            {
              "start_date": "2018-08-01",
              "end_date": "2018-08-31",
              "persons": 3
            }
+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            + date: "2018-08-14" (string) - date formated
            + state: 1 (number) - availabity state
            + floors (array)
                - (object)
                    + id: 7 (number)
                    + name: "MainFloor" (string)
                    + times (array)
                        - (object)
                            + id: 227480 (number)
                            + shift_category_id: 3 (number)


    + Body

            [
              {
                "date":"2018-08-14",
                "state":1,
                "floors":
                  [
                    {
                      "id":7,
                      "name":"MainFloor",
                      "times":
                        [
                          {
                            "id":227480,
                            "shift":"lunch",
                            "shift_category_id":3,
                            "start_time":"12:00",
                            "end_time":"16:00",
                            "guests":0,
                            "max_persons_capacity":25,
                            "all_turntimes":{"1":90}
                          },
                          {
                            "id":227273,
                            "shift":"dinner",
                            "shift_category_id":4,
                            "start_time":"19:00",
                            "end_time":"00:30",
                            "guests":0,
                            "max_persons_capacity":28,
                            "all_turntimes":{"1":90,"2":90,"3":90,"4":90,"5":90,"6":90}
                          },
                          {
                            "id":193265,
                            "shift":"dinner",
                            "shift_category_id":4,
                            "start_time":"19:00",
                            "end_time":"00:30",
                            "guests":7,
                            "max_persons_capacity":28,
                            "all_turntimes":{"1":90,"2":90,"3":90,"4":90,"5":90,"6":90}
                          }
                        ],
                      "slots":[]
                    },
                    {
                      "id":21,
                      "name":"SecondFloor",
                      "times":
                        [
                          {
                            "id":193267,
                            "shift":"Weinbar",
                            "shift_category_id":4,
                            "start_time":"17:00",
                            "end_time":"23:00",
                            "guests":0,
                            "max_persons_capacity":60,
                            "all_turntimes":{"1":60,"2":60,"3":60,"4":60,"5":60,"6":150}
                          }
                        ],
                        "slots":[]
                      }
                    ]
                  },
              {
                "date":"2018-08-15",
                "state":1,
                "floors":
                  [
                    {
                      "id":7,
                      "name":"MainFloor",
                      "times":
                        [
                          {
                            "id":193284,
                            "shift":"lunch",
                            "shift_category_id":3,
                            "start_time":"12:00",
                            "end_time":"16:00",
                            "guests":0,
                            "max_persons_capacity":25,
                            "all_turntimes":{"1":90}
                          },
                          {
                            "id":193285,
                            "shift":"dinner",
                            "shift_category_id":4,
                            "start_time":"19:00",
                            "end_time":"00:30",
                            "guests":0,
                            "max_persons_capacity":28,
                            "all_turntimes":{"1":90,"2":90,"3":90,"4":90,"5":90,"6":90}
                          }
                        ]
                      }
                    ]
                  }
            ]

# GET /restaurants/{restaurant_id}/slots
+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + persons (number, required) - the number of persons
    + shiftId (number, required) - Id of the shift

+ Response 200 (application/json)

    + Attributes (array)
        - (object)
            + time: "12:00" (string) - time formated
            + shift_category_id: 3 (number)
            + available: true (boolean)

    + Body

            [
              {
                "shift_category_id":3,
                "time":"12:00",
                "available":true
              },
              {
                "shift_category_id":3,
                "time":"12:15",
                "available":true
              },
              {
                "shift_category_id":3,
                "time":"12:30",
                "available":true
              }
            ]


# POST /restaurants/{restaurant_id}/bookings/create

+ Parameters
    + restaurant_id (string, required) - ID of the Restaurant in the form of a slug
    + locale (string, required) - the locale (de or en)
    + persons (number, required) - How many persons
    + user (User, required) - The first name of the main person

+ Request (application/json)

        {
              "persons": 2,
              "user" : {
                "firstname": "Martin",
                "lastname": "Wöginger",
                "email": "woeginger@exasoft.net",
                "gender": "male",
                "phone": "+491792404436",
                "restrictions": "Veganer",
                "restaurant_newsletter": true
              },
              "date": "2018-08-16",
              "time": "20:15",
              "sessionid": "f37681588d198288dec3bfd0ed",
              "isRequest": false,
              "shiftId": 193304,
              "cancel_limit": "10:00 Uhr am Tag vor der Buchung",
              "noshow_fee": "EUR 10",
              "notes_by_guest": "These are my notes"
          }
+ Response 200 (application/json)

    + Body

            {
              "success":true,
              "id":110504,
              "cancellation_token":"mut6FvW1pQtzwXYpeVsQ"
            }
